FROM node:22-alpine AS builder
WORKDIR /app

ARG REACT_APP_API_URL
ENV REACT_APP_API_URL=$REACT_APP_API_URL

COPY package*.json .
RUN npm install

COPY . .
RUN npm run build

FROM node:22-alpine
WORKDIR /app
RUN npm install -g serve
COPY --from=builder /app/build ./build
EXPOSE 3000
CMD ["serve", "-s", "build", "-l", "3000"]



# FROM node:22-alpine AS builder
# WORKDIR /app
# COPY package*.json .
# RUN npm install
# COPY . .
# RUN npm run build

# FROM node:22-alpine
# WORKDIR /app
# RUN npm install -g serve
# COPY --from=builder /app/build ./build
# EXPOSE 3000
# CMD ["serve", "-s", "build", "-l", "3000"]